sudo: required
language: node_js
node_js:
  - "8"
script:
  - chmod a+x downloadBinary.sh
  - ./downloadBinary.sh
  # - sudo add-apt-repository -y ppa:ethereum/ethereum
  # - sudo apt-get update
  # - sudo apt-cache policy solc
  # - sudo apt-get -y install solc
  # - sudo apt-get -y install solc
  - rm -rf contracts/games/Powerball.sol
  - npm install -g solidity-docgen
  - solidity-docgen /home/travis/build/FriendlyUser/solidity-smart-contracts /home/travis/build/FriendlyUser/solidity-smart-contracts/contracts /home/travis/build/FriendlyUser/solidity-smart-contracts
  - cd website
  - npm install
  - npm run build
  - cd ../
  - mv docs mddocs
  - mv mddocs website/build/solidity-smart-contracts
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: website/build/solidity-smart-contracts  # or remove this line to upload from root of repo
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
#after_script:
#  - npm run coverage && cat coverage/lcov.info | coveralls
