image: node:8.11.1

cache:
  paths:
  - node_modules/

stages:
  - test
  - deploy

truffle-tests:
  stage: test
  before_script:
   - npm i --save-dev run-with-testrpc
   - npm i truffle@4.1.4
   - npm install -g ganache-cli 
  script:
   - npm install
   -  ./node_modules/truffle/build/cli.bundled.js compile
   - ./node_modules/.bin/run-with-testrpc './node_modules/truffle/build/cli.bundled.js migrate && ./node_modules/truffle/build/cli.bundled.js test'
  allow_failure: true

frontEnd-tests:
  stage: test
  before_script:
   - npm i --save-dev run-with-testrpc 
   - npm i truffle jest
   - npm install -g ganache-cli
  script:
   - npm install
   - ./node_modules/truffle/build/cli.bundled.js compile
   #- npm run docs
   - ./node_modules/.bin/run-with-testrpc './node_modules/truffle/build/cli.bundled.js migrate && npm run test'